ci: fix cypress statuses perms (#36220)
Error: Action failed with error: HttpError: Resource not accessible by integration
https://github.com/mattermost/mattermost/pull/36178
(cherry picked from commit e5a723024213451932fddc68019693f480159afe)

Upstream: https://github.com/mattermost/mattermost/commit/e5a723024213451932fddc68019693f480159afe